# STM32F407 Discovery specific config
CONFIG_UART_STM32=y
CONFIG_CLOCK_STM32_SYSCLK_SRC_PLL=y
CONFIG_CLOCK_STM32_PLL_SRC_HSE=y
CONFIG_CLOCK_STM32_HSE_CLOCK=8000000
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=168000000
